### ISSUE TITLE
Archive project

### ISSUE THREAD

**Issue by lukaszkrzywizna** [fable-compiler/Fable.React.UseElmish#2]
Hi @alfonsogarciacaro ! First of all, thank you for a great work! I created this issue because I found there are two versions of `UseElmish` hook - this and `Feliz`. Based on [fable blog post](https://fable.io/blog/2022/2022-10-13-use-elmish.html) I assumes that Feliz's version is deprecated. Hovewer, later I found that the changes from here were moved to `Feliz` and any maintenance is continued by @Zaid-Ajaj. 

Having two same libraries is confusing - my company already used `Fable.React.UseElmish` and after discovering an error with [`useEffectOnce`](https://github.com/Zaid-Ajaj/Feliz/issues/540) were switched to the `Feliz.UseElmish`. To save time of the others, I suggest to archive this repo or at least put some note.

**Comment by MangelMaxime** [comment]
Hello @lukaszkrzywizna,

Thank you I just archived this repo and marked the package as deprecated on NuGet.
